# Generated by Django 6.0.1 on 2026-01-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_aboutus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='about_description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='about_heading',
            new_name='question',
        ),
    ]
