# Generated by Django 6.0.1 on 2026-02-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'About Us'},
        ),
    ]
