# Generated by Django 6.0.1 on 2026-01-24 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_blog_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_by_admins',
            field=models.ManyToManyField(blank=True, related_name='deleted_notifications_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by_admins',
            field=models.ManyToManyField(blank=True, related_name='read_notifications_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
