# Generated by Django 6.0.1 on 2026-01-24 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_notification_deleted_by_admins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_by_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_notifications_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
