# Generated by Django 6.0.1 on 2026-01-24 11:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_notification_deleted_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='images/cricket.jpg', null=True),
        ),
    ]
