# Generated by Django 6.0.1 on 2026-01-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_notification_assigned_admins_alter_blog_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='assigned_admins',
        ),
    ]
