# Generated by Django 6.0.1 on 2026-02-09 11:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='featured_image'),
        ),
    ]
